/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface TunnelConfig {
  /** Port to listen on */
  port: number
  /** Base path for routes (default: /__runner) */
  basePath?: string
  /** CORS allowed origins */
  corsOrigins?: Array<string>
}

/**
 * High-performance HTTP tunnel server powered by Rust
 *
 * @example
 * ```typescript
 * const server = new TunnelServer({
 *   port: 7070,
 *   basePath: '/__runner',
 *   corsOrigins: ['*']
 * });
 *
 * server.registerTask('app.tasks.add', async (input: any) => {
 *   return input.a + input.b;
 * });
 *
 * await server.listen();
 * ```
 */
export class TunnelServer {
  /**
   * Create a new tunnel server
   */
  constructor(config: TunnelConfig)

  /**
   * Register a task handler
   *
   * @param taskId - Unique task identifier (e.g., 'app.tasks.add')
   * @param handler - Async function that processes the task input
   *
   * @example
   * ```typescript
   * server.registerTask('app.tasks.calculate', async (input) => {
   *   return { result: input.a * input.b };
   * });
   * ```
   */
  registerTask(taskId: string, handler: (input: any) => Promise<any>): void

  /**
   * Register an event handler
   *
   * @param eventId - Unique event identifier (e.g., 'app.events.notify')
   * @param handler - Async function that processes the event payload
   *
   * @example
   * ```typescript
   * server.registerEvent('app.events.log', async (payload) => {
   *   console.log('Event received:', payload);
   * });
   * ```
   */
  registerEvent(eventId: string, handler: (payload: any) => Promise<void>): void

  /**
   * Start the HTTP server
   *
   * Returns a promise that resolves when the server is listening.
   * The server runs in the background and handles requests via Rust.
   *
   * @example
   * ```typescript
   * await server.listen();
   * console.log('Server is ready!');
   * ```
   */
  listen(): Promise<void>

  /**
   * Get list of registered task IDs
   *
   * @returns Array of task IDs
   */
  getTaskIds(): Promise<Array<string>>

  /**
   * Get list of registered event IDs
   *
   * @returns Array of event IDs
   */
  getEventIds(): Promise<Array<string>>
}
