blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/bluelibs/runner/discussions
    about: Ask how-to questions, share ideas, or discuss usage.
  - name: Security reports
    url: https://github.com/bluelibs/runner/blob/main/SECURITY.md
    about: Please follow our security policy for reporting vulnerabilities.

