import "./EventManager.test";
import "./tools/findCircularDependencies.test";
import "./ResourceInitializer.test";
import "./run.test";
import "./run.hooks.test";
import "./TaskRunner.test";
import "./globalEvents.test";
import "./Store.test";
import "./errors.test";
