/**
 * Generated by runner-dev new tag httpRoute
 * - Namespace: http
 * - File: src/http/tags/http-route.tag.ts
 */
import { tag } from "@bluelibs/runner";

export interface HttpRouteConfig {
  // Optional config carried by the tag (available via extract())
  method: "get" | "post" | "put" | "delete" | "patch" | "options" | "head";
  path: string;
}

export const httpRoute = tag<HttpRouteConfig>({
  id: "app.http.tags.http-route",
  meta: {
    title: "HTTP Route Tag",
    description: "Tag for marking tasks as HTTP endpoints with method and path configuration",
  },
});
