export { check, Match } from "./check/engine";
export type { CheckOptions } from "./check/engine";
export type {
  CheckSchemaLike,
  CheckedValue,
  InferCheckSchema,
  InferMatchPattern,
  MatchCompiledSchema,
  MatchMessageContext,
  MatchMessageOptions,
  MatchJsonObject,
  MatchJsonPrimitive,
  MatchJsonSchema,
  MatchJsonValue,
  MatchSchemaDecorator,
  MatchSchemaOptions,
  MatchClassDecorator,
  MatchClassOptions,
  MatchPropertyDecorator,
  MatchPattern,
  MatchToJsonSchemaOptions,
} from "./check/types";
export {
  CHECK_JSON_SCHEMA_UNSUPPORTED_PATTERN_ERROR_ID,
  type MatchFailure,
  MATCH_ERROR_ID,
  CHECK_INVALID_OPTIONS_ERROR_ID,
  CHECK_INVALID_PATTERN_ERROR_ID,
  createCheckJsonSchemaPatternError,
  createCheckOptionsError,
  createMatchError,
  createMatchPatternError,
  getMatchErrorMessage,
  isMatchError,
  rootFailure,
} from "./check/errors";
